import type { Metadata } from "next";
import './index.scss'
import Header from "../components/header/index"
import Footer from "../components/footer/index"
import Navbar from "../components/navbar/index"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={'x'}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
