### Login as admin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@cmms.com",
  "password": "Admin1234"
}

> {%
  client.global.set("accessToken", response.body.tokens.accessToken)
%}

### Get all locations (pobierz locationId)
GET http://localhost:3000/locations
Authorization: Bearer {{accessToken}}

> {% client.global.set("locationId", response.body[0].id) %}

### Set unique serial number
GET http://localhost:3000/
Authorization: Bearer {{accessToken}}

> {% client.global.set("serialNumber", "SN-" + Date.now()) %}

### Create machine
POST http://localhost:3000/machines
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "CNC Fanuc",
  "serialNumber": "{{serialNumber}}",
  "locationId": "{{locationId}}",
  "operatingHours": 0,
  "purchaseDate": "2024-01-01",
  "purchasePrice": 150000.00
}

> {% client.global.set("machineId", response.body.id) %}

### Get all machines
GET http://localhost:3000/machines
Authorization: Bearer {{accessToken}}

### Get machine by id
GET http://localhost:3000/machines/{{machineId}}
Authorization: Bearer {{accessToken}}

### Update machine
PATCH http://localhost:3000/machines/{{machineId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "CNC Fanuc - zaktualizowany"
}

### Update operating hours
PATCH http://localhost:3000/machines/{{machineId}}/operating-hours
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "operatingHours": 1500
}

### Get machine documents
GET http://localhost:3000/machines/{{machineId}}/documents
Authorization: Bearer {{accessToken}}

### Get machine TCO
GET http://localhost:3000/machines/{{machineId}}/tco
Authorization: Bearer {{accessToken}}

### Delete machine
DELETE http://localhost:3000/machines/{{machineId}}
Authorization: Bearer {{accessToken}}
