### Init
GET http://localhost:3000

> {% client.global.set("testEmail", "jan" + Date.now() + "@test.com") %}

### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Jan Kowalski",
  "email": "{{testEmail}}",
  "password": "Test1234"
}



### Me
GET http://localhost:3000/auth/me
Authorization: Bearer {{accessToken}}

### Logout
POST http://localhost:3000/auth/logout
Authorization: Bearer {{accessToken}}

### Refresh
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "token": "{{refreshToken}}"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "fetch@user.com",
  "password": "123456aA"
}

> {%
    client.global.set("accessToken", response.body.tokens.accessToken)
    client.global.set("refreshToken", response.body.tokens.refreshToken)
%}