### Login as admin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@cmms.com",
  "password": "Admin1234"
}

> {%
    client.global.set("accessToken", response.body.tokens.accessToken)
    client.global.set("refreshToken", response.body.tokens.refreshToken)
%}

### Create location
POST http://localhost:3000/locations
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Hala A",
  "type": "HALL"
}

> {% client.global.set("locationId", response.body.id) %}

### Get all locations
GET http://localhost:3000/locations
Authorization: Bearer {{accessToken}}

### Create machine
POST http://localhost:3000/machines
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "CNC Fanuc",
  "serialNumber": "SN-001-2024",
  "locationId": "{{locationId}}",
  "operatingHours": 0,
  "purchaseDate": "2024-01-01",
  "purchasePrice": 150000.00
}

> {% client.global.set("machineId", response.body.id) %}

### Get all machines
GET http://localhost:3000/machines
Authorization: Bearer {{accessToken}}

### Get machine by id
GET http://localhost:3000/machines/{{machineId}}
Authorization: Bearer {{accessToken}}

### Get machine TCO
GET http://localhost:3000/machines/{{machineId}}/tco
Authorization: Bearer {{accessToken}}
